=== LucaVN-KP/CustomermanagementBW/CustomerManagementBW/Schemas/XSDResponses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
	<element name="responses">
		<complexType>
			<sequence>
				<element name="response" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="method" type="string" maxOccurs="unbounded"/>
							<element name="sentence" maxOccurs="unbounded">
								<complexType>
									<simpleContent>
										<extension base="string">
											<attribute name="attribute" type="string" use="required"/>
										</extension>
									</simpleContent>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== LucaVN-KP/CustomermanagementBW/CustomerManagementBW/Schemas/Responses.xml
<?xml version="1.0" encoding="UTF-8"?>
<responses xmlns:tns='pippo' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation="XSDResponses.xsd">
	<response>
		<method>GET</method>
		<sentence attribute="OK">GET request successful</sentence>
		<sentence attribute="KO">GET request failed</sentence>
	</response>
	<response>
		<method>POST</method>
		<sentence attribute="OK">POST request successful</sentence>
		<sentence attribute="KO">POST request failed</sentence>
	</response>
</responses>
